#define KINECT_DISP 0.07	//measured
#define KINECT_X_VAR 50
#define KINECT_Y_VAR 50
#define KINECT_S_VAR 50
#define MOTION_FACTOR 1
#define TURN_FACTOR 1


#define OBSTACLE_FRONT 0 //2
#define OBSTACLE_SIDES 3
#define LEFT_AVAILABLE 5 //3
#define LEFT_AVAILABLE_SIDES 3
